name: Image & Icon
slug: image
groups: general
helpId: 5d1ff01304286369ad8d5f04
form:
  general:
    - name : image_fields_group
      label: Image
      type: fields-group
      status: open
      schema:
        - name: image
          type: media
          showstyle: true
          value: 'libraries/quix/assets/images/placeholder.png'
        
        - name: alt_text
          label : Alt Text
          type: text
          help : Google focuses on alt text when trying to understand what an image is about. So it's valuable for SEO, in addition to being useful for users.
          depends:
            image: '*'

        - name: caption
          type: text 
          depends:
            image: '*'
        
        - name: img_responsive
          label: Responsive
          type: switch
          value: true
    
    - name : image_links_fields_group
      label: Link
      type: fields-group
      schema:
        - name: link
          label: Link Url
          type: link
        
  styles:
    - name    : image_fields_group
      label   : Image
      type    : fields-group
      status  : open
      schema  :
        - name : alignment
          type : choose
          responsive : true
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right : 
              label : Right
              icon : qxuicon-align-right

        - name : width
          label : Width
          type: slider
          units: %, px
          defaultUnit: %
          max: 2000
          
        - name : height
          label : Height
          type: hidden
          units: %, px
          defaultUnit: px
          max: 2000
        
        - name : opacity
          label : Opacity
          type: slider
          responsive : false
          max : 1
          step: 0.1
          units: %
          defaultUnit:
    
    - name : border_fields_group
      label : Border
      type: fields-group
      schema :
        - name: img_border
          type: border

        - name : img_border_width
          label : Width
          type : hidden
        
        - name : img_border_type
          label : Border Type
          type: hidden
          value : none
          options: 
            none : None
            solid : Solid
            double : Double
            dotted : Dotted
            dashed : Dashed
        
        - name : img_border_color
          label : Border Color
          type : hidden 
        
        - name : img_border_radius
          label : Border Radius
          type: hidden

    - name    : icon_fields_group
      label   : Icon
      type    : fields-group
      schema  :
        - name: icon_color
          label: Icon Color
          type: color
          
        - name: icon_hover_color
          label: Icon Hover Color
          type: color

        - name : icon_padding
          label : Padding
          type: dimensions           

        - name: icon_bg_divider
          type: divider
          label: Background Color
        
        - name: icon_background
          type: background          

    - name    : caption_field_group
      label   : Caption
      type    : fields-group
      schema  :
        - name : caption_field_group_margin
          label : Margin
          type: dimensions

        - name : caption_field_group_padding
          label : Padding
          type: dimensions

        - name : caption_field_group_alignment
          label: Alignment
          type : hidden
          responsive : true
          options:
            left :
              label: Left
              icon : qxuicon-align-left
            center :
              label : Center
              icon : qxuicon-align-center
            right : 
              label : Right
              icon : qxuicon-align-right

        - name: caption_field_group_font
          label: Font
          type: typography

        - name  : caption_field_group_text_color
          label : Text Color
          type  : color
          value: rgba(0, 0, 0, 0.8)

        - name  : caption_field_group_background_color
          label : Background Color
          type  : hidden
          value: rgba(255, 255, 255, 0)

        - name: caption_bg_divider
          label: Background Color
          type: divider

        - name  : caption_background_color
          label : Background Color
          type  : background

        - name: caption_bd_divider
          label: Border
          type: divider

        - name  : caption_border
          label : Background Color
          type  : border          